### ISSUE TITLE
Would you mind pushing 0.0.3 to hex.pm?

### ISSUE THREAD

**Issue by mertonium** [pragdave/exexif#6]
Hello and thank you so much for this lib!

I had some trouble getting it running locally and then realized that [the package I got from hex is still at 0.0.1](https://hex.pm/packages/exexif/). 

Everything worked wonderfully once I changed my mix.exs to `{:exexif, git: "git@github.com:pragdave/exexif.git"}` but I thought I'd flag the discrepancy so others don't get caught out. 

I'm pretty sure `mix hex.publish` is all that needs to be run since [exexif's mix.exs](https://github.com/pragdave/exexif/blob/master/mix.exs#L6) has the updated version number.

Again, thanks for the hard work!

**Comment by pragdave** [comment]
Thanks for the nudge.

'tis done.
